version: '3'

services:
   nginx:
    container_name: nginx
    image: nginx:latest
    ports:
       - 80:80
       - 443:443
    volumes:
       - ./ssl:/etc/nginx/
       - ./jenkins.conf:/etc/nginx/conf.d/jenkins.conf
    networks:
      - jenkins_nexus

networks:
     jenkins_nexus:
        external: true



