version: '3'

services:
   nginx:
    container_name: nginx
    image: nginx:latest
    ports:
       - 80:80
       - 443:443
    volumes:
       - ./jenkins.conf:/etc/nginx/conf.d/jenkins.conf
       - ./ssl/example.key:/etc/nginx/example.key
       - ./ssl/example.crt:/etc/nginx/example.crt
    networks:
      - jenkins_nexus

networks:
     jenkins_nexus:
        external: true



