version: "3"

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    privileged: true
    user: root
    volumes:
      - "./nexus-data:/nexus-data"
    ports:
      - "8081:8081"
    networks:
      - jenkins_nexus

networks:
    jenkins_nexus:
         external: true
  
