---
# tasks file for install_jenkins

- name: Create directory for Jenkins 
  file:
    state: directory
    path: "/opt/jenkins"
    mode: '0755'

- name: Create jenkins data directory
  file:
    state: directory
    path: "/opt/jenkins/jenkins-data"
    mode: '0755'

- name: Copy docker-compose.yml
  copy: 
    src: docker-compose.yml
    dest: "/opt/jenkins"
    mode: '0644' 

- name: Create docker network
  shell: 'docker network create -d bridge --subnet=10.10.10.0/24 jenkins_nexus'


- name: Start jenkins
  shell: 'docker-compose -f /opt/jenkins/docker-compose.yml up -d'
  register: out
  

  
