---
# tasks file for install_jenkins

- name: Create directory for Jenkins 
  file:
    state: directory
    path: '/opt/jenkins'
    mode: '0755'

- name: Create jenkins data directory
  file:
    state: directory
    path: '/opt/jenkins/jenkins-data'
    mode: '0755'

- name: Create jenkins init directory
  file:
    state: directory
    path: '/opt/jenkins/jenkins-data/init.groovy.d'
    mode: '0644'

- name: Copy docker-compose.yml
  copy: 
    src: docker-compose.yml
    dest: '/opt/jenkins'
    mode: '0644' 

- name: Copy jenkins-cli.jar
  copy:
    src: jenkins-cli.jar
    dest: '/opt/jenkins/jenkins-data'
    mode: '0755'

- name: Copy groovy file for install maven
  copy:
    src: maven-install.groovy
    dest: '/opt/jenkins/jenkins-data/init.groovy.d'

- name: Copy groovy file for disable crumb
  copy:
    src: crumb-disable.groovy
    dest: '/opt/jenkins/jenkins-data/init.groovy.d'

- name: Copy config.xml for Jenkins job
  copy:
    src: config.xml
    dest: '/opt/jenkins/'

- name: Copy credentials.sh to create Nexus credentials
  copy:
    src: credentials.sh
    dest: '/opt/jenkins/'

- name: Script for change password Nexus
  copy:
    src: change_pass.sh
    dest: '/opt/jenkins/'

- name: Start jenkins
  shell: 'docker-compose -f /opt/jenkins/docker-compose.yml up -d'
  register: out

- name: Wait for start Jenkins
  wait_for: timeout=30

- name: Add nexus plugin
  shell: 'docker exec jenkins java -jar /var/jenkins_home/jenkins-cli.jar -s http://localhost:8080/ install-plugin nexus-artifact-uploader:2.13'

- name: Add pipeline plugin
  shell: 'docker exec jenkins java -jar /var/jenkins_home/jenkins-cli.jar -s http://localhost:8080/ install-plugin pipeline-stage-view:2.19'

- name: Add workflow plugin
  shell: 'docker exec jenkins java -jar /var/jenkins_home/jenkins-cli.jar -s http://localhost:8080/ install-plugin workflow-aggregator:2.6'

- name: Add pipeline plugin
  shell: 'docker exec jenkins java -jar /var/jenkins_home/jenkins-cli.jar -s http://localhost:8080/ install-plugin pipeline-utility-steps:2.8.0'

- name: Add GitHub Branch Source
  shell: 'docker exec jenkins java -jar /var/jenkins_home/jenkins-cli.jar -s http://localhost:8080/ install-plugin github-branch-source:2.10.4 -restart'

- name: Wait for restart Jenkins
  wait_for: timeout=60

- name: Change pass in file cretedials.sh
  shell: 'sh /opt/jenkins/change_pass.sh'

- name: Create credentials to nexus
  shell: 'sh /opt/jenkins/credentials.sh'
 
- name: Create job configuration
  uri:
    url: http://localhost:8080/createItem?name=jenkins-nexus
    method: POST
    src: config.xml
    headers:
      Content-Type: application/xml 

- name: Start job
  shell: 'docker exec jenkins java -jar /var/jenkins_home/jenkins-cli.jar -s http://localhost:8080/ build jenkins-nexus'
