---
# tasks file for install-nexus

- name: Create nexus directory
  file:
    state: directory
    path: '/opt/nexus'
    mode: '0755'

- name: Create nexus data directory
  file:
    state: directory
    path: '/opt/nexus/nexus-data'
    mode: '0755'

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: '/opt/nexus'
    mode: '0644'

- name: Create docker network
  shell: 'docker network create -d bridge --subnet=10.10.10.0/24 jenkins_nexus'

- name: Start nexus
  shell: 'docker-compose -f /opt/nexus/docker-compose.yml up -d'
